# Generated by Django 5.1.3 on 2025-03-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExtractedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("letter", "Letter"),
                            ("number", "Number"),
                            ("symbol", "Symbol"),
                        ],
                        max_length=10,
                    ),
                ),
                ("first_character", models.CharField(max_length=1)),
                (
                    "second_character",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "third_character",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "fourth_character",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["first_character", "second_character"],
                        name="DarkWebMana_first_c_3464c4_idx",
                    ),
                    models.Index(
                        fields=["third_character", "fourth_character"],
                        name="DarkWebMana_third_c_1bdadf_idx",
                    ),
                ],
            },
        ),
    ]
