# Generated by Django 5.1.3 on 2025-03-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DarkWebManagement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="extracteddata",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="extracteddata",
            name="h1",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="extracteddata",
            name="h2",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="extracteddata",
            name="h3",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="extracteddata",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="darkweb_images/"),
        ),
        migrations.AddField(
            model_name="extracteddata",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="darkweb_videos/"),
        ),
        migrations.AlterField(
            model_name="extracteddata",
            name="category",
            field=models.CharField(
                choices=[
                    ("letter", "Letter"),
                    ("number", "Number"),
                    ("symbol", "Symbol"),
                    ("image", "Image"),
                    ("video", "Video"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="extracteddata",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="extracteddata",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
