# Generated by Django 5.1.3 on 2025-03-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DarkWebManagement', '0002_extracteddata_description_extracteddata_h1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extracteddata',
            old_name='content',
            new_name='title_1',
        ),
        migrations.RenameField(
            model_name='extracteddata',
            old_name='h1',
            new_name='title_2',
        ),
        migrations.RenameField(
            model_name='extracteddata',
            old_name='h2',
            new_name='title_3',
        ),
        migrations.RemoveField(
            model_name='extracteddata',
            name='h3',
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='query',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
