# Generated by Django 5.1.3 on 2025-04-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DarkWebManagement", "0003_rename_content_extracteddata_title_1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="extracteddata",
            name="video",
        ),
        migrations.AddField(
            model_name="extracteddata",
            name="internal_links",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="extracteddata",
            name="category",
            field=models.CharField(
                choices=[
                    ("letter", "Letter"),
                    ("number", "Number"),
                    ("symbol", "Symbol"),
                    ("image", "Image"),
                ],
                max_length=10,
            ),
        ),
    ]
