# Generated by Django 5.1.3 on 2025-05-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DarkWebManagement', '0004_remove_extracteddata_video_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtractedData',
        ),
    ]
