# Generated by Django 5.1.3 on 2025-04-19 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255, unique=True)),
                ('first_character', models.CharField(max_length=1)),
                ('second_character', models.CharField(blank=True, max_length=1, null=True)),
                ('channel_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['first_character'], name='TelegramMan_first_c_d89ab5_idx'), models.Index(fields=['second_character'], name='TelegramMan_second__ca54be_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChannelIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1, unique=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TelegramManagement.channel')),
            ],
            options={
                'indexes': [models.Index(fields=['letter'], name='TelegramMan_letter_aaf934_idx')],
            },
        ),
    ]
