# Generated by Django 5.1.3 on 2025-04-19 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TelegramManagement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChannelIndex',
        ),
    ]
