# Generated by Django 5.1.3 on 2025-04-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TelegramManagement', '0002_delete_channelindex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='created_at',
            new_name='date_added',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='channel_id',
        ),
        migrations.AlterField(
            model_name='channel',
            name='first_character',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['channel_name'], name='TelegramMan_channel_a48f2b_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['date_added'], name='TelegramMan_date_ad_79c2eb_idx'),
        ),
    ]
