# Generated by Django 5.1.3 on 2025-04-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TelegramManagement', '0003_rename_created_at_channel_date_added_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='channel',
            name='TelegramMan_first_c_d89ab5_idx',
        ),
        migrations.RemoveIndex(
            model_name='channel',
            name='TelegramMan_second__ca54be_idx',
        ),
        migrations.RemoveIndex(
            model_name='channel',
            name='TelegramMan_channel_a48f2b_idx',
        ),
        migrations.RemoveIndex(
            model_name='channel',
            name='TelegramMan_date_ad_79c2eb_idx',
        ),
        migrations.AddField(
            model_name='channel',
            name='channel_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channel',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['channel_name', 'first_character', 'second_character'], name='TelegramMan_channel_82f68d_idx'),
        ),
    ]
