# Generated by Django 5.1.3 on 2025-04-25 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TelegramManagement', '0004_remove_channel_telegramman_first_c_d89ab5_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Channel',
        ),
    ]
