# Generated by Django 5.1.3 on 2024-12-30 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PasswordHash",
        ),
    ]
