# Generated by Django 5.1.3 on 2025-03-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PassManagement", "0004_a_first_character_a_fourth_character_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="b",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="b",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="b",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="b",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="c",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="c",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="c",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="c",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="d",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="d",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="d",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="d",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="e",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="e",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="e",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="e",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="f",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="f",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="f",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="f",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="g",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="g",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="g",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="g",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="h",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="h",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="h",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="h",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="i",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="i",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="i",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="i",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="j",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="j",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="j",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="j",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="k",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="k",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="k",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="k",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="l",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="l",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="l",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="l",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_a",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_a",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_a",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_a",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_b",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_b",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_b",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_b",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_c",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_c",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_c",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_c",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_d",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_d",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_d",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_d",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_e",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_e",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_e",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_e",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_f",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_f",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_f",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_f",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_g",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_g",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_g",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_g",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_h",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_h",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_h",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_h",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_i",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_i",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_i",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_i",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_j",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_j",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_j",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_j",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_k",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_k",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_k",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_k",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_l",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_l",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_l",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_l",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_m",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_m",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_m",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_m",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_n",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_n",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_n",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_n",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_o",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_o",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_o",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_o",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_p",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_p",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_p",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_p",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_q",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_q",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_q",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_q",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_r",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_r",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_r",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_r",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_s",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_s",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_s",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_s",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_t",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_t",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_t",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_t",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_u",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_u",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_u",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_u",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_v",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_v",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_v",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_v",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_w",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_w",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_w",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_w",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_x",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_x",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_x",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_x",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_y",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_y",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_y",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_y",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_z",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_z",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_z",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="lowercase_z",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="m",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="m",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="m",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="m",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="n",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="n",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="n",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="n",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="o",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="o",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="o",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="o",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="p",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="p",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="p",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="p",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="q",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="q",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="q",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="q",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="r",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="r",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="r",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="r",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="s",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="s",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="s",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="s",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="somthingelse",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="somthingelse",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="somthingelse",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="somthingelse",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="t",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="t",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="t",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="t",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_0",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_0",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_0",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_0",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_1",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_1",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_1",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_1",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_2",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_2",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_2",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_2",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_3",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_3",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_3",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_3",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_4",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_4",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_4",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_4",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_5",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_5",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_5",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_5",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_6",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_6",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_6",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_6",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_7",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_7",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_7",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_7",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_8",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_8",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_8",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_8",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_9",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_9",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_9",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="table_9",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="u",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="u",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="u",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="u",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="v",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="v",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="v",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="v",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="w",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="w",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="w",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="w",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="x",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="x",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="x",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="x",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="y",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="y",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="y",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="y",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="z",
            name="first_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="z",
            name="fourth_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="z",
            name="second_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="z",
            name="third_character",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddIndex(
            model_name="b",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_59f7b7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="b",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_ab24f4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="b",
            index=models.Index(fields=["hash"], name="PassManagem_hash_4f7ba2_idx"),
        ),
        migrations.AddIndex(
            model_name="c",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_6e7226_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="c",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_dfbd57_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="c",
            index=models.Index(fields=["hash"], name="PassManagem_hash_9d8e9a_idx"),
        ),
        migrations.AddIndex(
            model_name="d",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_3a2a9a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="d",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_6055a8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="d",
            index=models.Index(fields=["hash"], name="PassManagem_hash_c3f0fe_idx"),
        ),
        migrations.AddIndex(
            model_name="e",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_dce7b1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="e",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_265e17_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="e",
            index=models.Index(fields=["hash"], name="PassManagem_hash_bb8d84_idx"),
        ),
        migrations.AddIndex(
            model_name="f",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_d87bae_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="f",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_8c64bb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="f",
            index=models.Index(fields=["hash"], name="PassManagem_hash_30c6b5_idx"),
        ),
        migrations.AddIndex(
            model_name="g",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_7a6278_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="g",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_2459da_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="g",
            index=models.Index(fields=["hash"], name="PassManagem_hash_565fad_idx"),
        ),
        migrations.AddIndex(
            model_name="h",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_4d2df5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="h",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_d943ee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="h",
            index=models.Index(fields=["hash"], name="PassManagem_hash_b6d9f3_idx"),
        ),
        migrations.AddIndex(
            model_name="i",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_0c255a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="i",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_3810dc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="i",
            index=models.Index(fields=["hash"], name="PassManagem_hash_334b69_idx"),
        ),
        migrations.AddIndex(
            model_name="j",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_dfc98a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="j",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_cc5f58_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="j",
            index=models.Index(fields=["hash"], name="PassManagem_hash_70c7d6_idx"),
        ),
        migrations.AddIndex(
            model_name="k",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_952c55_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="k",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_a01dfa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="k",
            index=models.Index(fields=["hash"], name="PassManagem_hash_98c5b4_idx"),
        ),
        migrations.AddIndex(
            model_name="l",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_6b2196_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="l",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_970be0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="l",
            index=models.Index(fields=["hash"], name="PassManagem_hash_421f56_idx"),
        ),
        migrations.AddIndex(
            model_name="lowercase_a",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_18efc3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_a",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_75b0af_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_a",
            index=models.Index(fields=["hash"], name="PassManagem_hash_2696c9_idx"),
        ),
        migrations.AddIndex(
            model_name="lowercase_b",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_765bac_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_b",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_51299c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_b",
            index=models.Index(fields=["hash"], name="PassManagem_hash_79eb37_idx"),
        ),
        migrations.AddIndex(
            model_name="lowercase_c",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_a0d86e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_c",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_fdd03a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_c",
            index=models.Index(fields=["hash"], name="PassManagem_hash_d4ed6a_idx"),
        ),
        migrations.AddIndex(
            model_name="lowercase_d",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_87e544_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_d",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_60132d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_d",
            index=models.Index(fields=["hash"], name="PassManagem_hash_011837_idx"),
        ),
        migrations.AddIndex(
            model_name="lowercase_e",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_5d3e97_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_e",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_09de5d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_e",
            index=models.Index(fields=["hash"], name="PassManagem_hash_f3cac1_idx"),
        ),
        migrations.AddIndex(
            model_name="lowercase_f",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_a94a76_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_f",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_0a234e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_f",
            index=models.Index(fields=["hash"], name="PassManagem_hash_e4b192_idx"),
        ),
        migrations.AddIndex(
            model_name="lowercase_g",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_6fbdc2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_g",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_ab26f9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_g",
            index=models.Index(fields=["hash"], name="PassManagem_hash_02d4dd_idx"),
        ),
        migrations.AddIndex(
            model_name="lowercase_h",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_2b124d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_h",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_87e80a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_h",
            index=models.Index(fields=["hash"], name="PassManagem_hash_591151_idx"),
        ),
        migrations.AddIndex(
            model_name="lowercase_i",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_9b191c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_i",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_33c0ed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_i",
            index=models.Index(fields=["hash"], name="PassManagem_hash_33d688_idx"),
        ),
        migrations.AddIndex(
            model_name="lowercase_j",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_82f372_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_j",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_b15ea9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_j",
            index=models.Index(fields=["hash"], name="PassManagem_hash_26e267_idx"),
        ),
        migrations.AddIndex(
            model_name="lowercase_k",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_13ff7d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_k",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_b61b37_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_k",
            index=models.Index(fields=["hash"], name="PassManagem_hash_92731c_idx"),
        ),
        migrations.AddIndex(
            model_name="lowercase_l",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_d683c1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_l",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_1caf27_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_l",
            index=models.Index(fields=["hash"], name="PassManagem_hash_c3018c_idx"),
        ),
        migrations.AddIndex(
            model_name="lowercase_m",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_539879_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_m",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_b444ec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_m",
            index=models.Index(fields=["hash"], name="PassManagem_hash_baa9de_idx"),
        ),
        migrations.AddIndex(
            model_name="lowercase_n",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_19c98c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_n",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_3af49b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_n",
            index=models.Index(fields=["hash"], name="PassManagem_hash_778037_idx"),
        ),
        migrations.AddIndex(
            model_name="lowercase_o",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_6e8c66_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_o",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_cb8740_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_o",
            index=models.Index(fields=["hash"], name="PassManagem_hash_e8b1a3_idx"),
        ),
        migrations.AddIndex(
            model_name="lowercase_p",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_9eda99_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_p",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_d87f20_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_p",
            index=models.Index(fields=["hash"], name="PassManagem_hash_da5cfb_idx"),
        ),
        migrations.AddIndex(
            model_name="lowercase_q",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_27646a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_q",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_ec24a2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_q",
            index=models.Index(fields=["hash"], name="PassManagem_hash_a27dc5_idx"),
        ),
        migrations.AddIndex(
            model_name="lowercase_r",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_02c805_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_r",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_5e300f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_r",
            index=models.Index(fields=["hash"], name="PassManagem_hash_bdf165_idx"),
        ),
        migrations.AddIndex(
            model_name="lowercase_s",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_46533e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_s",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_ca26a2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_s",
            index=models.Index(fields=["hash"], name="PassManagem_hash_665cd7_idx"),
        ),
        migrations.AddIndex(
            model_name="lowercase_t",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_1414ff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_t",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_be611d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_t",
            index=models.Index(fields=["hash"], name="PassManagem_hash_e81b30_idx"),
        ),
        migrations.AddIndex(
            model_name="lowercase_u",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_ac290f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_u",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_5dd7c8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_u",
            index=models.Index(fields=["hash"], name="PassManagem_hash_0a9406_idx"),
        ),
        migrations.AddIndex(
            model_name="lowercase_v",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_9d71b9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_v",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_efd4dd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_v",
            index=models.Index(fields=["hash"], name="PassManagem_hash_d710ca_idx"),
        ),
        migrations.AddIndex(
            model_name="lowercase_w",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_3a2a5a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_w",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_69f612_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_w",
            index=models.Index(fields=["hash"], name="PassManagem_hash_de2b26_idx"),
        ),
        migrations.AddIndex(
            model_name="lowercase_x",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_db64a9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_x",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_d5af6a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_x",
            index=models.Index(fields=["hash"], name="PassManagem_hash_7ca3c1_idx"),
        ),
        migrations.AddIndex(
            model_name="lowercase_y",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_f6ed55_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_y",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_9d4fd1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_y",
            index=models.Index(fields=["hash"], name="PassManagem_hash_9df1b8_idx"),
        ),
        migrations.AddIndex(
            model_name="lowercase_z",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_fbd116_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_z",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_2fe418_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lowercase_z",
            index=models.Index(fields=["hash"], name="PassManagem_hash_ddbab5_idx"),
        ),
        migrations.AddIndex(
            model_name="m",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_ab87a5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="m",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_c2059a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="m",
            index=models.Index(fields=["hash"], name="PassManagem_hash_1c212e_idx"),
        ),
        migrations.AddIndex(
            model_name="n",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_1af773_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="n",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_04a8bf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="n",
            index=models.Index(fields=["hash"], name="PassManagem_hash_dd8db8_idx"),
        ),
        migrations.AddIndex(
            model_name="o",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_efa3a4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="o",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_cf2646_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="o",
            index=models.Index(fields=["hash"], name="PassManagem_hash_498424_idx"),
        ),
        migrations.AddIndex(
            model_name="p",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_cf7c17_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="p",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_1296c6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="p",
            index=models.Index(fields=["hash"], name="PassManagem_hash_73254a_idx"),
        ),
        migrations.AddIndex(
            model_name="q",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_a6a7e2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="q",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_d79e31_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="q",
            index=models.Index(fields=["hash"], name="PassManagem_hash_91b03a_idx"),
        ),
        migrations.AddIndex(
            model_name="r",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_6564c9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="r",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_1f4079_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="r",
            index=models.Index(fields=["hash"], name="PassManagem_hash_0743a7_idx"),
        ),
        migrations.AddIndex(
            model_name="s",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_6c2811_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="s",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_8814e8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="s",
            index=models.Index(fields=["hash"], name="PassManagem_hash_2c2aa7_idx"),
        ),
        migrations.AddIndex(
            model_name="somthingelse",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_d0caea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="somthingelse",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_0101ee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="somthingelse",
            index=models.Index(fields=["hash"], name="PassManagem_hash_eabcb4_idx"),
        ),
        migrations.AddIndex(
            model_name="t",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_42873f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="t",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_4d75db_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="t",
            index=models.Index(fields=["hash"], name="PassManagem_hash_3acdfa_idx"),
        ),
        migrations.AddIndex(
            model_name="table_0",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_374c93_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="table_0",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_2f6f15_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="table_0",
            index=models.Index(fields=["hash"], name="PassManagem_hash_dbe1ec_idx"),
        ),
        migrations.AddIndex(
            model_name="table_1",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_57b3ff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="table_1",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_d9d096_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="table_1",
            index=models.Index(fields=["hash"], name="PassManagem_hash_5bad11_idx"),
        ),
        migrations.AddIndex(
            model_name="table_2",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_c6786b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="table_2",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_fedf51_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="table_2",
            index=models.Index(fields=["hash"], name="PassManagem_hash_c8adba_idx"),
        ),
        migrations.AddIndex(
            model_name="table_3",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_9312d3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="table_3",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_22d033_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="table_3",
            index=models.Index(fields=["hash"], name="PassManagem_hash_edb400_idx"),
        ),
        migrations.AddIndex(
            model_name="table_4",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_e86100_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="table_4",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_de2ddb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="table_4",
            index=models.Index(fields=["hash"], name="PassManagem_hash_325418_idx"),
        ),
        migrations.AddIndex(
            model_name="table_5",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_70c89b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="table_5",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_e08dd7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="table_5",
            index=models.Index(fields=["hash"], name="PassManagem_hash_759e86_idx"),
        ),
        migrations.AddIndex(
            model_name="table_6",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_186af2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="table_6",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_ae62ec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="table_6",
            index=models.Index(fields=["hash"], name="PassManagem_hash_21079c_idx"),
        ),
        migrations.AddIndex(
            model_name="table_7",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_d4235a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="table_7",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_b75c06_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="table_7",
            index=models.Index(fields=["hash"], name="PassManagem_hash_306903_idx"),
        ),
        migrations.AddIndex(
            model_name="table_8",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_ad08b6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="table_8",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_38315e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="table_8",
            index=models.Index(fields=["hash"], name="PassManagem_hash_11f031_idx"),
        ),
        migrations.AddIndex(
            model_name="table_9",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_65d58a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="table_9",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_c9836c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="table_9",
            index=models.Index(fields=["hash"], name="PassManagem_hash_75358c_idx"),
        ),
        migrations.AddIndex(
            model_name="u",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_0137b4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="u",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_f71a67_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="u",
            index=models.Index(fields=["hash"], name="PassManagem_hash_540cb2_idx"),
        ),
        migrations.AddIndex(
            model_name="v",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_53f32f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="v",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_52b603_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="v",
            index=models.Index(fields=["hash"], name="PassManagem_hash_871c2d_idx"),
        ),
        migrations.AddIndex(
            model_name="w",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_e1661c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="w",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_66a39a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="w",
            index=models.Index(fields=["hash"], name="PassManagem_hash_0982cf_idx"),
        ),
        migrations.AddIndex(
            model_name="x",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_1a4535_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="x",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_ac21fa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="x",
            index=models.Index(fields=["hash"], name="PassManagem_hash_fa0936_idx"),
        ),
        migrations.AddIndex(
            model_name="y",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_88577a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="y",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_958b0e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="y",
            index=models.Index(fields=["hash"], name="PassManagem_hash_8a3c97_idx"),
        ),
        migrations.AddIndex(
            model_name="z",
            index=models.Index(
                fields=["first_character", "second_character"],
                name="PassManagem_first_c_3f19dd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="z",
            index=models.Index(
                fields=["third_character", "fourth_character"],
                name="PassManagem_third_c_72b537_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="z",
            index=models.Index(fields=["hash"], name="PassManagem_hash_4c7de7_idx"),
        ),
    ]
