from django.contrib import admin
from .models import *

# Register your models here.
admin.site.register(A)
admin.site.register(B)
admin.site.register(C)
admin.site.register(D)
admin.site.register(E)
admin.site.register(F)
admin.site.register(G)
admin.site.register(H)
admin.site.register(I)
admin.site.register(J)
admin.site.register(K)
admin.site.register(L)
admin.site.register(M)
admin.site.register(N)
admin.site.register(O)
admin.site.register(P)
admin.site.register(Q)
admin.site.register(R)
admin.site.register(S)
admin.site.register(T)
admin.site.register(U)
admin.site.register(V)
admin.site.register(W)
admin.site.register(X)
admin.site.register(Y)
admin.site.register(Z)
###########################
admin.site.register(Lowercase_a)
admin.site.register(Lowercase_b)
admin.site.register(Lowercase_c)
admin.site.register(Lowercase_d)
admin.site.register(Lowercase_e)
admin.site.register(Lowercase_f)
admin.site.register(Lowercase_g)
admin.site.register(Lowercase_h)
admin.site.register(Lowercase_i)
admin.site.register(Lowercase_j)
admin.site.register(Lowercase_k)
admin.site.register(Lowercase_l)
admin.site.register(Lowercase_m)
admin.site.register(Lowercase_n)
admin.site.register(Lowercase_o)
admin.site.register(Lowercase_p)
admin.site.register(Lowercase_q)
admin.site.register(Lowercase_r)
admin.site.register(Lowercase_s)
admin.site.register(Lowercase_t)
admin.site.register(Lowercase_u)
admin.site.register(Lowercase_v)
admin.site.register(Lowercase_w)
admin.site.register(Lowercase_x)
admin.site.register(Lowercase_y)
admin.site.register(Lowercase_z)
###########################
admin.site.register(table_0)
admin.site.register(table_1)
admin.site.register(table_2)
admin.site.register(table_3)
admin.site.register(table_4)
admin.site.register(table_5)
admin.site.register(table_6)
admin.site.register(table_7)
admin.site.register(table_8)
admin.site.register(table_9)
############################
admin.site.register(SomthingElse)

admin.site.site_header='Database Administrator'
admin.site.site_title='Hawk Eye'